import { Rujukan } from "../models";

export const dummyRujukanData: Rujukan[] = [
  {
    id: 1,
    referenceNumber: "REF1",
    date: "2023-09-30",
    nik: "NIK1",
    patientType: "PatientType1",
    patientName: "PatientName1",
    doctorName: "DoctorName1",
    location: "Location1",
    referenceLocation: "ReferenceLocation1",
    polyName: "PolyName1",
    diagnose: "Diagnose1",
    medicine: "Medicine1",
    actionsTaken: "ActionsTaken1",
    referenceReason: "ReferenceReason1",
  },
  {
    id: 2,
    referenceNumber: "REF2",
    date: "2023-09-28",
    nik: "NIK2",
    patientType: "PatientType2",
    patientName: "PatientName2",
    doctorName: "DoctorName2",
    location: "Location2",
    referenceLocation: "ReferenceLocation2",
    polyName: "PolyName2",
    diagnose: "Diagnose2",
    medicine: "Medicine2",
    actionsTaken: "ActionsTaken2",
    referenceReason: "ReferenceReason2",
  },
  {
    id: 3,
    referenceNumber: "REF3",
    date: "2023-09-24",
    nik: "NIK3",
    patientType: "PatientType3",
    patientName: "PatientName3",
    doctorName: "DoctorName3",
    location: "Location3",
    referenceLocation: "ReferenceLocation3",
    polyName: "PolyName3",
    diagnose: "Diagnose3",
    medicine: "Medicine3",
    actionsTaken: "ActionsTaken3",
    referenceReason: "ReferenceReason3",
  },
  {
    id: 4,
    referenceNumber: "REF4",
    date: "2023-09-20",
    nik: "NIK4",
    patientType: "PatientType4",
    patientName: "PatientName4",
    doctorName: "DoctorName4",
    location: "Location4",
    referenceLocation: "ReferenceLocation4",
    polyName: "PolyName4",
    diagnose: "Diagnose4",
    medicine: "Medicine4",
    actionsTaken: "ActionsTaken4",
    referenceReason: "ReferenceReason4",
  },
  {
    id: 5,
    referenceNumber: "REF5",
    date: "2023-09-18",
    nik: "NIK5",
    patientType: "PatientType5",
    patientName: "PatientName5",
    doctorName: "DoctorName5",
    location: "Location5",
    referenceLocation: "ReferenceLocation5",
    polyName: "PolyName5",
    diagnose: "Diagnose5",
    medicine: "Medicine5",
    actionsTaken: "ActionsTaken5",
    referenceReason: "ReferenceReason5",
  },
  {
    id: 6,
    referenceNumber: "REF6",
    date: "2023-09-16",
    nik: "NIK6",
    patientType: "PatientType6",
    patientName: "PatientName6",
    doctorName: "DoctorName6",
    location: "Location6",
    referenceLocation: "ReferenceLocation6",
    polyName: "PolyName6",
    diagnose: "Diagnose6",
    medicine: "Medicine6",
    actionsTaken: "ActionsTaken6",
    referenceReason: "ReferenceReason6",
  },
  {
    id: 7,
    referenceNumber: "REF7",
    date: "2023-09-14",
    nik: "NIK7",
    patientType: "PatientType7",
    patientName: "PatientName7",
    doctorName: "DoctorName7",
    location: "Location7",
    referenceLocation: "ReferenceLocation7",
    polyName: "PolyName7",
    diagnose: "Diagnose7",
    medicine: "Medicine7",
    actionsTaken: "ActionsTaken7",
    referenceReason: "ReferenceReason7",
  },
  {
    id: 8,
    referenceNumber: "REF8",
    date: "2023-09-12",
    nik: "NIK8",
    patientType: "PatientType8",
    patientName: "PatientName8",
    doctorName: "DoctorName8",
    location: "Location8",
    referenceLocation: "ReferenceLocation8",
    polyName: "PolyName8",
    diagnose: "Diagnose8",
    medicine: "Medicine8",
    actionsTaken: "ActionsTaken8",
    referenceReason: "ReferenceReason8",
  },
  {
    id: 9,
    referenceNumber: "REF9",
    date: "2023-09-08",
    nik: "NIK9",
    patientType: "PatientType9",
    patientName: "PatientName9",
    doctorName: "DoctorName9",
    location: "Location9",
    referenceLocation: "ReferenceLocation9",
    polyName: "PolyName9",
    diagnose: "Diagnose9",
    medicine: "Medicine9",
    actionsTaken: "ActionsTaken9",
    referenceReason: "ReferenceReason9",
  },
  {
    id: 10,
    referenceNumber: "REF10",
    date: "2023-09-06",
    nik: "NIK10",
    patientType: "PatientType10",
    patientName: "PatientName10",
    doctorName: "DoctorName10",
    location: "Location10",
    referenceLocation: "ReferenceLocation10",
    polyName: "PolyName10",
    diagnose: "Diagnose10",
    medicine: "Medicine10",
    actionsTaken: "ActionsTaken10",
    referenceReason: "ReferenceReason10",
  },
];
